---
# tasks file for ansible-role-edgeos-firewall
- name: Set fact
  set_fact:
    router_firewall_config_list: []
    router_zone_config_list: []
    firewall_rules_merged: "{{ firewall_rules }}"

- name: Gather router facts
  edgeos_facts:
    gather_subset: all

- name: Look up additional firewall rules
  vars:
    query: '[].name'
  set_fact:
    firewall_rules_extra: "{{ (firewall_rules_extra|default([])) + lookup('vars','firewall_rules_'+item,default=[]) }}"
  loop: "{{ firewall_zones | json_query(query) }}"
  when:
    - firewall_process_rules|bool or firewall_cleanup|bool
    - lookup('vars','firewall_rules_'+item, default=[])|length > 0

- name: Merge firewall rules
  set_fact:
    firewall_rules_merged: "{{ firewall_rules + firewall_rules_extra }}"
  when:
    - firewall_process_rules|bool or firewall_cleanup|bool
    - firewall_rules_extra|default([])|length > 0

- name: Add missing converse rule sets for ipv4
  vars:
    fw_zone_names: "{{ firewall_zones | json_query('[].name') }}"
    fw_ruleset_names: "{{ firewall_rules_merged | json_query('[].name') }}"
  set_fact:
    firewall_rules_merged: "{{ firewall_rules_merged + [{'name':item[1]+'-'+item[0]}] }}"
  with_cartesian:
    - "{{ fw_zone_names }}"
    - "{{ fw_zone_names }}"
  when:
    - item[0] != item[1]
    - (item[0]+'-'+item[1]) in fw_ruleset_names
    - not (item[1]+'-'+item[0]) in fw_ruleset_names
    - firewall_add_converse_rulesets|bool
    - firewall_process_rules|bool or firewall_cleanup|bool

- name: Add missing converse rule sets for ipv6
  vars:
    fw_zone_names: "{{ firewall_zones | json_query('[].name') }}"
    fw_ruleset_names: "{{ firewall_rules_merged | json_query('[].name') }}"
  set_fact:
    firewall_rules_merged: "{{ firewall_rules_merged + [{'name':item[1]+'-'+item[0]+'-v6'}] }}"
  with_cartesian:
    - "{{ fw_zone_names }}"
    - "{{ fw_zone_names }}"
  when:
    - item[0] != item[1]
    - (item[0]+'-'+item[1]+'-v6') in fw_ruleset_names
    - not (item[1]+'-'+item[0]+'-v6') in fw_ruleset_names
    - firewall_add_converse_rulesets_v6|bool
    - firewall_process_rules|bool or firewall_cleanup|bool

- block:
  - name: Populate list of router firewall base properties (fast)
    vars:
      regex: "set firewall (?:ipv6-){0,1}name ([a-zA-Z0-9-_]+) (?!rule)(.*)"
      populate_type: firewall_rule_base_properties
    set_fact:
      router_firewall_config_list: "{{ router_firewall_config_list|default([]) + lookup('template', 'build_lookup.j2') }}"
    when: firewall_process_rules|bool or firewall_cleanup|bool

  - name: Populate list of router firewall rule properties (fast)
    vars:
      regex: "set firewall (?:ipv6-){0,1}name ([a-zA-Z0-9-_]+) rule (\\d+) (.*)"
      populate_type: firewall_rule_properties
    set_fact:
      router_firewall_config_list: "{{ router_firewall_config_list|default([]) + lookup('template', 'build_lookup.j2') }}"
    when: firewall_process_rules|bool or firewall_cleanup|bool

  - name: Populate list of router zone base properties (fast)
    vars:
      regex: "set zone-policy zone ([a-zA-Z0-9-_]+) (?!from)(.*)"
      populate_type: zone_base_properties
    set_fact:
      router_zone_config_list: "{{ router_zone_config_list|default([]) + lookup('template', 'build_lookup.j2') }}"
    when: firewall_process_zones|bool

  - name: Populate list of router zone properties (fast)
    vars:
      regex: "set zone-policy zone ([a-zA-Z0-9-_]+) from ([a-zA-Z0-9-_]+) firewall ((?:ipv6-){0,1}name) ([a-zA-Z0-9-_]+)"
      populate_type: zone_properties
    set_fact:
      router_zone_config_list: "{{ router_zone_config_list|default([]) + lookup('template', 'build_lookup.j2') }}"
    when: firewall_process_zones|bool
  when: firewall_fast_lookup|bool

- name: Run legacy lookups
  include_tasks: legacy_lookup.yaml
  when: not firewall_fast_lookup|bool

- block:
  - name: Display generic lines
    vars:
      lines: "{{ firewall_commands }}"
    debug:
      var: lines
    when: firewall_commands|length > 0

  - name: Display cleanup lines
    vars:
      lines: "{{ lookup('template', 'firewall_cleanup.j2').splitlines() }}"
    debug:
      var: lines

  - name: Display firewall lines
    vars:
      lines: "{{ lookup('template', 'firewall_main.j2').splitlines() }}"
    debug:
      var: lines

  - name: Display zones lines
    vars:
      lines: "{{ lookup('template', 'zones.j2').splitlines() }}"
    debug:
      var: lines

  when: not firewall_commit|bool

- block:
  - name: Execute generic lines
    edgeos_config:
      lines: "{{ firewall_commands }}"
    when: firewall_commands|length > 0

  - name: Clean up firewall rule sets and content that are not in config
    edgeos_config:
      lines: "{{ lookup('template', 'firewall_cleanup.j2').splitlines() }}"
    when: firewall_cleanup|bool
  
  - name: Apply firewall rules
    edgeos_config:
      lines: "{{ lookup('template', 'firewall_main.j2').splitlines() }}"
    when: firewall_process_rules|bool
  
  - name: Apply zone configuration
    edgeos_config:
      lines: "{{ lookup('template', 'zones.j2').splitlines() }}"
    when: firewall_process_zones
  when:
    - not firewall_combine_apply|bool
    - firewall_commit|bool

- name: Apply all configuration changes
  edgeos_config:
    lines: "{{ firewall_commands + lookup('template', 'firewall.j2').splitlines() }}"
  when:
    - firewall_combine_apply|bool
    - firewall_commit|bool
